export default [
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        global: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly'
      }
    },
    rules: {
      // Possible errors
      'no-console': 'warn',
      'no-debugger': 'error',
      'no-dupe-args': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': 'error',
      'no-extra-semi': 'error',
      'no-func-assign': 'error',
      'no-inner-declarations': 'error',
      'no-irregular-whitespace': 'error',
      'no-obj-calls': 'error',
      'no-sparse-arrays': 'error',
      'no-unreachable': 'error',
      'valid-typeof': 'error',

      // Best practices
      'array-callback-return': 'error',
      'block-scoped-var': 'error',
      'class-methods-use-this': 'warn',
      'consistent-return': 'error',
      'curly': ['error', 'all'],
      'default-case': 'warn',
      'dot-notation': 'error',
      'eqeqeq': ['error', 'always'],
      'no-alert': 'error',
      'no-caller': 'error',
      'no-div-regex': 'error',
      'no-else-return': 'warn',
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-floating-decimal': 'error',
      'no-global-assign': 'error',
      'no-implied-eval': 'error',
      'no-iterator': 'error',
      'no-labels': 'error',
      'no-lone-blocks': 'error',
      'no-loop-func': 'error',
      'no-magic-numbers': ['warn', { ignore: [0, 1, -1] }],
      'no-multi-spaces': 'error',
      'no-multi-str': 'error',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-wrappers': 'error',
      'no-octal': 'error',
      'no-octal-escape': 'error',
      'no-param-reassign': 'error',
      'no-proto': 'error',
      'no-redeclare': 'error',
      'no-return-assign': 'error',
      'no-script-url': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-throw-literal': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unused-expressions': 'error',
      'no-unused-labels': 'error',
      'no-useless-call': 'error',
      'no-useless-concat': 'error',
      'no-useless-escape': 'error',
      'no-useless-return': 'error',
      'no-void': 'error',
      'no-warning-comments': 'warn',
      'no-with': 'error',
      'prefer-promise-reject-errors': 'error',
      'radix': 'error',
      'require-await': 'error',
      'vars-on-top': 'error',
      'wrap-iife': 'error',
      'yoda': 'error',

      // Variables
      'no-catch-shadow': 'error',
      'no-delete-var': 'error',
      'no-label-var': 'error',
      'no-restricted-globals': 'error',
      'no-shadow': 'error',
      'no-shadow-restricted-names': 'error',
      'no-undef': 'error',
      'no-undef-init': 'error',
      'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      'no-use-before-define': 'error',

      // Node.js
      'callback-return': 'error',
      'global-require': 'error',
      'handle-callback-err': 'error',
      'no-buffer-constructor': 'error',
      'no-mixed-requires': 'error',
      'no-new-require': 'error',
      'no-path-concat': 'error',
      'no-process-env': 'warn',
      'no-process-exit': 'error',
      'no-restricted-modules': 'error',
      'no-sync': 'warn',

      // Stylistic
      'array-bracket-newline': ['error', 'consistent'],
      'array-bracket-spacing': 'error',
      'array-element-newline': ['error', 'consistent'],
      'block-spacing': 'error',
      'brace-style': ['error', '1tbs', { allowSingleLine: true }],
      'camelcase': 'error',
      'capitalized-comments': 'off',
      'comma-dangle': ['error', 'never'],
      'comma-spacing': 'error',
      'comma-style': 'error',
      'computed-property-spacing': 'error',
      'consistent-this': 'error',
      'eol-last': 'error',
      'func-call-spacing': 'error',
      'func-name-matching': 'error',
      'func-names': 'warn',
      'func-style': ['error', 'expression'],
      'function-paren-newline': ['error', 'consistent'],
      'id-blacklist': 'off',
      'id-length': 'off',
      'id-match': 'off',
      'implicit-arrow-linebreak': 'error',
      'indent': ['error', 2, { SwitchCase: 1 }],
      'jsx-quotes': 'off',
      'key-spacing': 'error',
      'keyword-spacing': 'error',
      'line-comment-position': 'off',
      'linebreak-style': 'error',
      'lines-around-comment': 'off',
      'lines-between-class-members': 'error',
      'max-depth': 'warn',
      'max-len': ['warn', { code: 100, ignoreUrls: true }],
      'max-lines': 'off',
      'max-lines-per-function': 'off',
      'max-nested-callbacks': 'warn',
      'max-params': 'warn',
      'max-statements': 'off',
      'max-statements-per-line': 'error',
      'multiline-comment-style': 'off',
      'multiline-ternary': 'off',
      'new-cap': 'error',
      'new-parens': 'error',
      'newline-per-chained-call': 'error',
      'no-array-constructor': 'error',
      'no-bitwise': 'error',
      'no-continue': 'off',
      'no-inline-comments': 'off',
      'no-lonely-if': 'error',
      'no-mixed-operators': 'error',
      'no-mixed-spaces-and-tabs': 'error',
      'no-multi-assign': 'error',
      'no-multiple-empty-lines': ['error', { max: 2 }],
      'no-negated-condition': 'off',
      'no-nested-ternary': 'error',
      'no-new-object': 'error',
      'no-plusplus': 'off',
      'no-restricted-syntax': 'error',
      'no-tabs': 'error',
      'no-ternary': 'off',
      'no-trailing-spaces': 'error',
      'no-underscore-dangle': 'off',
      'no-unneeded-ternary': 'error',
      'no-whitespace-before-property': 'error',
      'nonblock-statement-body-position': 'error',
      'object-curly-newline': ['error', { consistent: true }],
      'object-curly-spacing': 'error',
      'object-property-newline': ['error', { allowMultiplePropertiesPerLine: true }],
      'one-var': ['error', 'never'],
      'one-var-declaration-per-line': 'error',
      'operator-assignment': 'error',
      'operator-linebreak': 'error',
      'padded-blocks': ['error', 'never'],
      'padding-line-between-statements': 'error',
      'prefer-object-spread': 'error',
      'quote-props': ['error', 'as-needed'],
      'quotes': ['error', 'single', { avoidEscape: true }],
      'semi': 'error',
      'semi-spacing': 'error',
      'semi-style': 'error',
      'sort-keys': 'off',
      'sort-vars': 'off',
      'space-before-blocks': 'error',
      'space-before-function-paren': ['error', 'always'],
      'space-in-parens': 'error',
      'space-infix-ops': 'error',
      'space-unary-ops': 'error',
      'spaced-comment': 'error',
      'switch-colon-spacing': 'error',
      'template-tag-spacing': 'error',
      'unicode-bom': 'error',
      'wrap-regex': 'error'
    }
  },
  {
    files: ['tests/**/*.js'],
    rules: {
      'no-console': 'off',
      'no-unused-expressions': 'off'
    }
  }
];
